### ISSUE TITLE
Connect New Domain https://LinkForIsrael.com/

### ISSUE THREAD

**Issue by 4tal** [4tal/ConnectPortal#16]

**Comment by ohadschn** [comment]
IMHO some domain that is easier to remember/type would be more important than ".com" (and also cheaper)
Just a random example, `israel.in` is available for less than 10$ / year
You can quickly find similar results here: https://www.namecheap.com/domains/registration/results/?domain=israel

**Comment by 4tal** [comment]
israel.in taken.
Bought israelink.xyz

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain

**Comment by 4tal** [comment]
Switched To linksforisrael.com
