### ISSUE TITLE
Move TODOs to Github Issues

### ISSUE THREAD

**Issue by 4tal** [4tal/ConnectPortal#20]

**Comment by liranprof** [comment]
Moving your TODOs to GitHub can help you better manage and track your tasks within a version control system. Here's a step-by-step guide on how to do it:

1. **Create a GitHub Repository**:
   - If you don't have a GitHub account, sign up for one.
   - Create a new repository on GitHub where you'll store your TODOs. You can make it public or private, depending on your needs.

2. **Set Up a Local Git Repository**:
   - If you haven't already, install Git on your computer.
   - Open your terminal or command prompt and navigate to the directory where you have your TODOs or the project related to them.

3. **Initialize Git**:
   - Run the following command to initialize a Git repository in your project folder:
     ```
     git init
     ```

4. **Create a README File**:
   - Create a README.md file in your project folder. This file will serve as the main document where you'll add your TODOs.

5. **Add TODOs to README.md**:
   - Open the README.md file in a text editor.
   - Start adding your TODOs using Markdown syntax. You can use lists, headings, and checkboxes to organize and mark the status of each task.

6. **Stage and Commit Changes**:
   - Run the following commands to stage and commit your changes:
     ```
     git add README.md
     git commit -m "Initial TODO list"
     ```

7. **Link Your Local Repository to GitHub**:
   - Go to your GitHub repository and click on the "Code" button.
   - Copy the URL of your GitHub repository (it should be in the format `https://github.com/username/repository-name.git`).

8. **Set Up a Remote Repository**:
   - In your terminal, link your local Git repository to the GitHub repository by running the following command (replace the URL with your repository's URL):
     ```
     git remote add origin https://github.com/username/repository-name.git
     ```

9. **Push Your TODOs to GitHub**:
   - Push your local changes to the GitHub repository:
     ```
     git push -u origin main
     ```
   - Replace `main` with the branch name if you're using a different branch.

10. **Access Your TODOs on GitHub**:
    - Visit your GitHub repository on the web. You'll find your README.md file with your TODOs listed there.

11. **Manage and Update Your TODOs on GitHub**:
    - You can edit your README.md file directly on GitHub to add, modify, or complete tasks.
    - GitHub provides a rich interface for task management, including checkboxes to mark tasks as done.

By following these steps, you can easily move your TODOs to GitHub, making it convenient to manage and collaborate on your tasks with others if needed.

This chatgpt answer

**Comment by ohadschn** [comment]
@4tal at work we have a hybrid - we open work items / issues but keep the TODO in the code, referencing them. Example:
```
// TODO make configurable https://github.com/4tal/ConnectPortal/issues/123
int foo = 42 
```

**Comment by 4tal** [comment]
Done
