### ISSUE TITLE
Add the Needs Database

### ISSUE THREAD

**Issue by ohadschn** [4tal/ConnectPortal#31]
Verified by the Microsoft Israel NGO/association contact owner: 
https://forms.monday.com/forms/25c5ac9f7676f6ffbf7fae7b982e87ef?r=use1

יוזמה לאומית רחבה מאוד שכוללת את פיקוד העורף, מטה ההתנדבות הלאומי, האגודה למען החייל, הג'ויינט, הפורום הכלכלי חברתי ועוד

**Comment by 4tal** [comment]
<img width="1045" alt="image" src="https://github.com/4tal/ConnectPortal/assets/6404507/debf5c7f-33ef-4e49-a40a-bb07780e91e4">

**Comment by ohadschn** [comment]
Where did it go ???
This is one of the biggest initiatives as far as I know...
