### ISSUE TITLE
Remove all specific donation causes, only keep link to: https://naboo.ai/safedonate/

### ISSUE THREAD

**Issue by ohadschn** [4tal/ConnectPortal#32]
This is their specialty, and it doesn't make sense to have specific causes verified by ConnectPortal - it's duplicate, needless work.

**Comment by 4tal** [comment]
<img width="849" alt="image" src="https://github.com/4tal/ConnectPortal/assets/6404507/71df9c6f-ec79-4249-b5e6-0216bbbfbe8b">
