### ISSUE TITLE
Drop "technical help / development" to the bottom

### ISSUE THREAD

**Issue by ohadschn** [4tal/ConnectPortal#35]
Our focus should be users, not would-be collaborators (that we probably don't even need at this point).
This section is currently taking up the most precious real estate.

For similar reasons, I'd lower the `Tech` category too.

**Comment by 4tal** [comment]
<img width="1055" alt="image" src="https://github.com/4tal/ConnectPortal/assets/6404507/15d78ed5-0ef2-48f1-9eeb-edfd42bba645">
